name: deploy-auth

on:
  push:
    branches:
      - master
    # paths:
    #   - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - run: cd auth && docker build -t delwinrbest/auth .
      - run: docker push delwinrbest/auth
