name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Authentic doctl with Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - name: Create kubectl Context
        run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - name: Init Infra Update
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
