name: deploy-payments

on:
  push:
    branches:
      - master
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build Container Image
        run: cd payments && docker build -t delwinrbest/payments .
      - name: Push Image to Docker Hub
        run: docker push delwinrbest/payments
      - name: Login doctl with Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - name: Create kubectl Context
        run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - name: Init Deployment
        run: kubectl rollout restart deployment payments-depl
